# memo:サービスとして起動しておく、ぐらいの設定です
version: "3"
services:
  scraping:
    container_name: docker-py-scraping
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - .:/app